# Generated by Django 4.1.2 on 2023-12-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientForm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.CharField(blank=True, max_length=100, null=True)),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
                ("cpf", models.CharField(blank=True, max_length=100, null=True)),
                ("card", models.CharField(blank=True, max_length=100, null=True)),
                ("time", models.CharField(blank=True, max_length=100, null=True)),
                ("hoster", models.CharField(blank=True, max_length=100, null=True)),
                ("store", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "file",
                    models.FileField(null=True, upload_to="files/", verbose_name=""),
                ),
            ],
        ),
    ]
